version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/infrastructure"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "terraform"
    commit-message:
      prefix: "deps(terraform)"
    groups:
      terraform:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/back"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "rust"
    commit-message:
      prefix: "deps(rust)"
    groups:
      cargo:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/front"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "deps(npm)"
    groups:
      npm:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "deps(actions)"
    groups:
      github-actions:
        patterns:
          - "*"
