name: CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - infrastructure/**
      - .github/workflows/infrastructure-ci.yml

permissions:
  actions: write
  contents: read
  pull-requests: write

env:
  TF_IN_AUTOMATION: "true"
  TF_CLI_ARGS: "-no-color"
  TF_VAR_repository_full_name: ${{ github.repository }}
  TF_VAR_repository_token: ${{ github.token }}
  TF_VAR_neon_api_token: ${{ secrets.TF_VAR_NEON_API_TOKEN }}
  TF_VAR_neon_org_id: ${{ vars.NEON_ORG_ID }}
  TF_VAR_render_owner_id: ${{ vars.RENDER_OWNER_ID }}
  RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
  BETTERUPTIME_API_TOKEN: ${{ secrets.BETTERUPTIME_API_TOKEN }}

jobs:
  lint_plan_and_comment:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93 # v6.2.2

      - name: Restore Terraform state cache
        uses: actions/cache/restore@v4
        with:
          path: infrastructure/terraform.tfstate
          key: terraform-local-state-main

      - name: Terraform fmt check
        run: make fmt

      - name: TFLint
        run: make lint

      - name: Plan
        run: make init plan show-plan

      - name: Post sticky plan diff
        uses: marocchino/sticky-pull-request-comment@0ea0beb66eb9baf113663a64ec522f60e49231c0 # v3.0.4
        with:
          header: terraform-plan
          path: infrastructure/plan.txt
